## Assignment2

1. Arithmetic operators
2. Relational operators
3. Logical operators
4. Assignment operators
5. Identity operators
5. if elif else statements
6. Loops
7. break vs continue
8. Functions
9. lambda expressions
10. Map
11. filter
12. reduce
13. List Comprehensions
14. files
15. exceptions
16. classes and objects
17. numpy

## Operators


### Arithmetic operators

In [1]:
a= 100
b =15
# addition 
result = a+b
print("result after adding a and b is", result)
# subtraction
result = a-b
print("result after subtracting a and b is", result)
#multiplication
result = a*b
print("result after multiplying a and b is", result)
#Division
result = a/b
print("result after Dividing a and b is", result)
# modulus
result = a%b
print("result after  a modulus b is", result)

result after adding a and b is 115
result after subtracting a and b is 85
result after multiplying a and b is 1500
result after Dividing a and b is 6.666666666666667
result after  a modulus b is 10


In [2]:
#The "+" can also be used to concatenate two strings or lists
list_1 = ['d','a','t']
list_2 = ['a','_','M','L']
result = list_1 + list_2
print(result)
## To know more about lists and strings please refer my pythonNotes1

['d', 'a', 't', 'a', '_', 'M', 'L']


In [3]:
1 > 2

False

In [4]:
1 < 2

True

In [5]:
1 >= 1

True

In [6]:
1 <= 4

True

In [7]:
1 == 1

True

### Logical Operators
and

or

not

In [8]:
# A and B returns true if both expression A and B returns True else returns false
(1 > 2) and (2 < 3)

False

In [9]:
# A and B returns true if atleast one of expression A and B is True else 
# returns false
(1 > 2) or (2 < 3)

True

In [10]:
not((1 > 2) or (2 < 3))

False

### Assignment operators

In [11]:
# "+=", Adds right side value to left side value and then assigns new value to 
# the left side variable
a = 10
b = 5
a+=b
print("value of a after performing a+=b is"," ",a)
# "-=", Subtracts right side value with leftside value and then assigns new value to 
# the left side variable

a = 10
b= 5
a-=b
print("value of a after performing a-=b is"," ",a)
# "*=", Multiplies right side value with leftside value and then assigns new value to 
# the left side variable
a = 10
b= 5
a *= b 
print("value of a after performing a*=b is"," ",a)
# "**=" calculates left side value raise to the power of right side value and assigns 
# it to leftside value
a = 10
b= 5
a **= b 
print("value of a after performing a**=b is"," ",a)

value of a after performing a+=b is   15
value of a after performing a-=b is   5
value of a after performing a*=b is   50
value of a after performing a**=b is   100000


### Identity operators

"in" and "not in"

In [12]:
#x"in" y :outputs true if it finds x in sequence Y, false otherwise

In [13]:
X  =  2
Y = [1, 2, 3]
print("output for X(2) in Y([1, 2, 3]) is"," ",X in Y)

output for X(2) in Y([1, 2, 3]) is   True


In [14]:
#x"not in" y :outputs true if it finds x in sequence Y, false otherwise

In [15]:
X  =  2
Y = [1, 2, 3]
print("output for X(2) not in Y([1, 2, 3]) is"," ",X not in Y)

output for X(2) not in Y([1, 2, 3]) is   False


Extra Info:
Apart from the above mentioned operators; Python also has
5. Bitwise operators
6. Membership operators


## If elif else statements
if condition:
  
  //code

elif condition:
  
  //code
  
else:
  
  //code

In [16]:
a = 100
b = 50

if a > b:
    print("a>b")
elif(a == b):
    print("a=b")
else:
    print("a<b")

a>b


In [17]:
number = int(input("enter number \n"))

enter number 
2


In [18]:
if(number >= 1 and number <= 10):
    print("number between 1 to 10")
elif(number >= 11 and number <= 20):
    print("number between 11 to 20")
elif(number >= 21 and number <= 30):
    print("number between 20 to 30")
else:
    print("number greater than 30")

number between 1 to 10


### for loop: 

defined as

for i in iterable:
        
        code
where iterable can be list or list of lists or defined by range(x) 

In [19]:
my_list = range(3)

In [20]:
for i in my_list:
    print(i)

0
1
2


In [21]:
my_list = [1, 2, 3]

In [22]:
for i in my_list:
    print(i)

1
2
3


In [23]:
my_list = ['a', 'b', 'c']

In [24]:
for i in range(len(my_list)):
    print (i)

0
1
2


In [25]:
# nested for loops
for i in range(2):
    for j in range(2):
      print (i*j)

0
0
0
1


In [26]:
#forloops and if statements
my_list = range(20)
even_list = []
odd_list = []

for i in my_list:
    if(i % 2 ==0):
        even_list.append(i)
    else:
        odd_list.append(i)

print('list of even numbers are', even_list)
print('list of odd numbers are',odd_list)

list of even numbers are [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
list of odd numbers are [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [27]:
numb_3 = []
numb_5 = []
numb_7 = []
numb_others =[]

for i in my_list:
    if(i % 3 ==0):
        numb_3.append(i)
    elif(i % 5 ==0):
        numb_5.append(i)
    elif(i % 7 ==0):
        numb_7.append(i)
    else:
        numb_others.append(i)

In [28]:
numb_3

[0, 3, 6, 9, 12, 15, 18]

In [29]:
numb_5

[5, 10]

In [30]:
numb_7

[7, 14]

In [31]:
numb_others

[1, 2, 4, 8, 11, 13, 16, 17, 19]

### while loop:
defined as:

while condition:
   
     /code/ 
    
In contrast to far, while loop checks the condition for every iteration 

In [32]:
count = 0
while count < 2:
    print("Data Science")
    count+=1

Data Science
Data Science


In [33]:
# while and if statements)
even_list = []
odd_list = []
i=0
while i < 20:
    if(i % 2 ==0):
        even_list.append(i)
    else:
        odd_list.append(i)
    i+=1

print('list of even numbers are', even_list)
print('list of odd numbers are',odd_list)

list of even numbers are [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
list of odd numbers are [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


### break vs continue; 
break is used to when you want to end the loop if certain condition is met

continue is used if you don't want to run the entire loop for certain condition

In [34]:
#here you want to come out of the loop once the sum becomes zero. 
#so, break is used
sum = 0
print('value for i is')
for i in range(-2, 4):
    sum = sum+i
    print(i)
    if(sum == 0):
        print('sum is equal to zero')
        break

value for i is
-2
-1
0
1
2
sum is equal to zero


In [35]:
# Continue: Here you want to divide the  sum with i; Here you don't want to execute 
# the division statement only for i =0
print('value for i is')
for i in range(-2, 4):
    if(i == 0): 
        continue
    print(i,"\t")
    sum = sum/i

value for i is
-2 	
-1 	
1 	
2 	
3 	


## List Comprehensions
It is defined by List(expression (for loop with one or more conditions))

In [36]:
list_1 = [j for j in range(4)]

In [37]:
list_1

[0, 1, 2, 3]

In [38]:
#squaring the first 10 numbers; here we have only one condition
list_1 = [i*i for i in range(10)]

In [39]:
list_1

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [40]:
#Squaring the even numbers in first 10 numbers; here we have more than 
# one condition 
list_2 = [i*i for i in range(10) if i%2 == 0]

In [41]:
list_2

[0, 4, 16, 36, 64]

In [42]:
## nested for loops;  outer loop will be followed by inner loops

list_2 = [(j, k) for j in range(2) for k in range(2)]

In [43]:
list_2

[(0, 0), (0, 1), (1, 0), (1, 1)]

In [44]:
list_2 = [j for j in range(4) for k in range(j)]

In [45]:
list_2

[1, 2, 2, 3, 3, 3]

In [46]:
list_2 = [(j, k) for j in range(4) for k in range(j)]

list_2


[(1, 0), (2, 0), (2, 1), (3, 0), (3, 1), (3, 2)]

## Functions
function declaration: def keyword is used

 def func_name:  
 
     /code/

In [47]:
# function definition
def my_function():
    print("Sample function definition")

In [48]:
# function call
my_function()

Sample function definition


In [49]:
def add(a, b):
    return a+b

In [50]:
add(20, 30)

50

In [51]:
# nested loops

## Lambda expressions

It is defined as 

lambda arguments : expression

It can have any number of arguments but only once expression

In [52]:
lambda_declaration = lambda x: x * 2

In [53]:
lambda_declaration(4)

8

In [54]:
#addition using lambda expressions and functions

In [55]:
add = lambda x, y : x+y

def add_func(x, y):
    return(x+y)

In [56]:
add(2, 3)

5

In [57]:
add_func(2,3)

5

## lambdas vs functions
1. Lambda expressions can be used as a replacement for functions especially in case of operations between numbers.
2. Lambdas makes writing code a bit easier and a bit cleaner
3. lambda expressions are mainly used along with map, filter, reduce

In [58]:
# factorial declaration in function
def factorial(x):
    if x == 1:
        return 1
    else:
        x= x-1
        return(x*factorial(x))

In [59]:
# factorial declaration in lambda
factorial_lambda = lambda x:x ** 2

In [60]:
print(factorial(2))

1


In [61]:
factorial_lambda(8)

64

## map() 
It is used to make transformations to the existing elements in datastructure

map is defined by  map(function, seq1, seq2,...);
seq1, seq2 can be list or tuple or set or..

In [62]:
list_1 = [1, 2, 3]
newlist_map = map(lambda x:x+2, list_1) 

In [63]:
list(newlist_map)

[3, 4, 5]

In [64]:
list_2 = ['data','science','machine','learning' ]

In [65]:
newlist2_map = map(lambda x:x+" test", list_2)

In [66]:
list_2

['data', 'science', 'machine', 'learning']

In [67]:
list(newlist2_map)

['data test', 'science test', 'machine test', 'learning test']

In [68]:
#performing operation on lists

list(map(lambda x,y:str(x) + " "+y , list_1, list_2))

['1 data', '2 science', '3 machine']

## filter() 
if you want to filter a data with some condition for example, suppose if you want to find only even numbers from a given list

defined as: filter(condition/filtering function, sequence)

sequence can be list or tuple or set

It also returns a sequence of elements; filter function can only have one iterable/sequence as input


In [69]:
list_1 = [1, 5, 4, 6, 8, 11, 3, 12]

In [70]:
new_list = filter(lambda x: x%2 == 0 , list_1)

In [71]:
print(list(new_list))

[4, 6, 8, 12]


In [72]:
list_2 = ['1', '5', '4', '6', '8', '11', '3', '12']

In [73]:
new_list_2 = filter(lambda x: int(x)%2 == 0 , list_2)

In [74]:
list(new_list_2)

['4', '6', '8', '12']

In [75]:
"right" >= "left"

True

In [76]:
"right" < "rih"

True

In [77]:
##List of dictionaries

In [78]:
dict_list = [{1:'DataScience',2:'ml',3:'AI'},{1:'DataScience',2:'ml'}]

In [79]:
even_dict = filter(lambda x:len(x)%2 == 0, dict_list)

In [80]:
list(even_dict)

[{1: 'DataScience', 2: 'ml'}]

## reduce() ; 

It is used to return a single value from a given set of elements(list/sets/..)

It is defined by reduce(func, sequence)

Sequence can be list/set/tuple

func is the operation that needs to repeatedly performed on all elements in sequence

In [81]:
import functools as fn
 
# importing operator for operator functions
import operator as op

In [82]:
(fn.reduce(op.mul,list_1))

380160

In [83]:
(fn.reduce(op.add,list_2))

'1546811312'

## files

In [84]:
# creating a new file

f = open("samplefile.txt", "w+")

In [85]:
for i in range(10):
    f.write("this is line"+" "+str(i)+"\n")

In [86]:
f.close()

In [87]:
f = open("samplefile.txt", "r")

In [88]:
for i in range(5):
    print(f.readline(), end = ","),

this is line 0
,this is line 1
,this is line 2
,this is line 3
,this is line 4
,

In [89]:
f.close()

## Exception Handling

In [90]:
#exception handling
while True:
    try:
        n = input("Please enter an integer: ")
        n = int(n)
        break
    except ValueError:
        print("No valid integer! Please try again ...")
print("Great, you successfully entered an integer!")

Please enter an integer: w
No valid integer! Please try again ...
Please enter an integer: 2
Great, you successfully entered an integer!


In [91]:
try:
    x = int(input("Your number: "))
    inverse = 1.0 / x
except ValueError:
    print("You should have given either an int or a float")
except ZeroDivisionError:
    print("Infinity")
finally:
    print("There may or may not have been an exception.")

Your number: 0
Infinity
There may or may not have been an exception.


In [92]:
try:
    f = open("tf")
except:
    print("file not found error")

file not found error


In [93]:
try:
    f = open("tf")
except FileNotFoundError:
    print("file not found error")
except:
    print("error")

file not found error


In [94]:
try:
    x = int(input("Your number: "))
    inverse = 1.0 / x
    try:
        f = open("tf")
    except FileNotFoundError:
            print("file not found error")
    except:
            print("error")
except ValueError:
    print("You should have given either an int or a float")
except ZeroDivisionError:
    print("Infinity")
finally:
    print("There may or may not have been an exception.")

Your number: 2
file not found error
There may or may not have been an exception.


In [95]:
try:
    x = int(input("Your number: "))
    inverse = 1.0 / x
except ValueError:
    print("You should have given either an int or a float")
    try:
        print("checking try inside except")
    except:
        print("except inside except")
except ZeroDivisionError:
    print("Infinity")
finally:
    print("There may or may not have been an exception.")

Your number: w
You should have given either an int or a float
checking try inside except
There may or may not have been an exception.


## Classes and Objects

In [96]:
# creating a class
class class1:
    my_variable = "This is my first class"
    def myfunction(self):
        print("my function")
        print("my_variable"+"\t"+self.my_variable)

In [97]:
## creating objects

In [98]:
obj1 = class1()

In [99]:
obj1.myfunction()

my function
my_variable	This is my first class


In [100]:
obj1.my_variable = "replacing the value"

In [101]:
obj1.my_variable

'replacing the value'

In [102]:
obj1.myfunction()

my function
my_variable	replacing the value


In [103]:
obj2 = class1()

In [104]:
obj2.myfunction()

my function
my_variable	This is my first class


### Inheritance

In [105]:
class parent:
    parentname = "great"
    def __init__(self):
        print("constructor called")

In [106]:
obj1 = parent()

constructor called


In [107]:
class parent:
    parentname = "great"
    def __init__(self, a):
        print("parameterised constructor called")

In [108]:
var = x;
obj1 = parent(x)

parameterised constructor called


In [109]:
#if two default constructors were given, it takes the latter one(child one)

class parent:
    parentname = "great"
    def __init__(self):
        print("constructor called")
    def test1(self, a):
        print("parameterised constructor called")
class child1(parent):
    def test(self):
        print("child constructor")

In [110]:
obj = child1()

constructor called


In [111]:
obj.test1(2)

parameterised constructor called


In [112]:
##try abstracts & interfaces java

## Tupples

In [113]:
from collections import namedtuple

In [114]:
color = namedtuple('color',['r','g','b'])

In [115]:
color = color(r=1,g=2,b=3)

In [116]:
color

color(r=1, g=2, b=3)

In [117]:
color.r

1

In [118]:
color.g

2

### Regular Expression

In [119]:
import re
result = re.match(r'Analytics', 'AR Aribah Analytics AR')

In [120]:
print(result)

None


In [121]:
# match
result = re.match(r'AR', 'ARibah Analytics')
print(result.group())
print(result.start())
print(result.end())

AR
0
2


In [122]:
result = re.match(r'Analytics', 'Analytics')
print(result)

<_sre.SRE_Match object; span=(0, 9), match='Analytics'>


In [123]:
print(result.group())

Analytics


In [124]:
# search
result = re.search('Analytics', 'AR Aribah Analytics AR')
print(result.group())

Analytics


In [125]:
result = re.findall(r'AR', 'AR ARibah Analytics AR')
print(result)

['AR', 'AR', 'AR']


In [126]:
result = re.split(r'i','DataScience Machine Learning')

In [127]:
result

['DataSc', 'ence Mach', 'ne Learn', 'ng']

In [128]:
result = re.split(r'i','DataScience Machine Learning', maxsplit = 1)

In [129]:
result

['DataSc', 'ence Machine Learning']

In [130]:
data = 'Data Science and Machine Learning'
match = re.search(r'\w+i\w+', data)
if match:
    print(match.group())
else:
    print("no match")

Science


#numpy

In [131]:
import numpy as np
a = np.zeros(10)

a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [132]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [133]:
a = np.arange(10,50)

a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [134]:
a= np.arange((9)).reshape(3,3)

a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])